# Generated by Django 2.1.5 on 2020-02-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='upload_photos')),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Like', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('Date', models.DateField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capturer.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='Tag',
            field=models.ManyToManyField(to='capturer.Tag'),
        ),
    ]
