# Generated by Django 2.1.5 on 2020-02-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
