# Generated by Django 2.1.5 on 2020-02-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0002_auto_20200223_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
