# Generated by Django 2.1.5 on 2020-02-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0003_auto_20200223_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
