# Generated by Django 2.1.5 on 2020-02-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
