# Generated by Django 2.1.5 on 2020-02-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
