# Generated by Django 2.1.5 on 2020-02-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0008_auto_20200225_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
