# Generated by Django 2.1.5 on 2020-02-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0009_auto_20200225_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
