# Generated by Django 2.1.5 on 2020-02-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0011_auto_20200225_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='capturer.Photo'),
            preserve_default=False,
        ),
    ]
