# Generated by Django 2.1.5 on 2020-02-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0016_auto_20200225_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
