# Generated by Django 2.1.5 on 2020-02-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0019_auto_20200225_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Title',
        ),
    ]
