# Generated by Django 2.1.5 on 2020-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0020_remove_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
