# Generated by Django 2.1.5 on 2020-02-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0022_auto_20200225_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='Title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
