# Generated by Django 2.1.5 on 2020-02-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0023_auto_20200226_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
