# Generated by Django 2.1.5 on 2020-02-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0026_favoritephoto_userfollowing_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritephoto',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='review',
        ),
        migrations.DeleteModel(
            name='FavoritePhoto',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
