# Generated by Django 2.1.5 on 2020-02-27 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0028_favoritephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritephoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
