# Generated by Django 2.1.5 on 2020-02-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0030_auto_20200227_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(related_name='user_favoirte', to='capturer.Photo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review',
            field=models.ManyToManyField(related_name='user_review', to='capturer.Photo'),
        ),
    ]
