# Generated by Django 2.1.5 on 2020-02-27 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0032_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_favoirte', to='capturer.Photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='review',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_review', to='capturer.Photo'),
        ),
    ]
