# Generated by Django 2.1.5 on 2020-02-27 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0034_auto_20200227_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
