# Generated by Django 2.1.5 on 2020-02-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0036_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
