# Generated by Django 2.1.5 on 2020-02-28 01:08

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0037_auto_20200227_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ManyToManyField(related_name='user_favoirte', to='capturer.UserProfile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='review',
            field=models.ManyToManyField(related_name='user_review', to='capturer.Photo'),
        ),
    ]
