# Generated by Django 2.1.5 on 2020-02-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0038_auto_20200228_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='review',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(related_name='user_favoirte', to='capturer.Photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ManyToManyField(related_name='user_review', to='capturer.UserProfile'),
        ),
    ]
