# Generated by Django 2.1.5 on 2020-02-28 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capturer', '0039_auto_20200228_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
