# Generated by Django 2.1.5 on 2020-03-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0043_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_favoirte', to='capturer.Photo'),
        ),
    ]
