# Generated by Django 2.1.5 on 2020-03-05 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0044_auto_20200305_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
