# Generated by Django 2.1.5 on 2020-03-06 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0045_auto_20200305_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(related_name='user_favoirte', to='capturer.Photo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
