# Generated by Django 2.1.5 on 2020-03-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0046_auto_20200306_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Image',
        ),
    ]
