# Generated by Django 2.1.5 on 2020-03-07 00:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0048_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
