# Generated by Django 2.1.5 on 2020-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0049_auto_20200307_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
