# Generated by Django 2.1.5 on 2020-03-07 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0050_auto_20200307_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
