# Generated by Django 2.1.5 on 2020-03-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0051_auto_20200307_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
