# Generated by Django 2.1.5 on 2020-03-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capturer', '0053_temp_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_photo',
        ),
    ]
